services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "cinema_app"
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stock_db
      - POSTGRES_DB=cinema_db

  db:
    image: postgres
    restart: always
    container_name: "cinema_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=stock_db
    expose:
      - 5432